export const ALL_MQTT_TOPICS = [
  { topic: 'teslamate/cars/1/display_name' },
  { topic: 'teslamate/cars/1/state' },
  { topic: 'teslamate/cars/1/battery_level' },
  { topic: 'teslamate/cars/1/ideal_battery_range_km' },
  { topic: 'teslamate/cars/1/est_battery_range_km' },
  { topic: 'teslamate/cars/1/plugged_in' },
  { topic: 'teslamate/cars/1/charge_limit_soc' },
  { topic: 'teslamate/cars/1/scheduled_charging_start_time' },
  { topic: 'teslamate/cars/1/charge_energy_added' },
  { topic: 'teslamate/cars/1/speed' },
  { topic: 'teslamate/cars/1/outside_temp' },
  { topic: 'teslamate/cars/1/inside_temp' },
  { topic: 'teslamate/cars/1/locked' },
  { topic: 'teslamate/cars/1/sentry_mode' },
];
